<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="TestSuite" Id="{a7e22833-6c27-466d-9ad3-520ef4a39cff}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TestSuite EXTENDS FB_TestSuite

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TestSuite">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>