<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="BrokenCalculator" Id="{6503d53b-0719-4282-bbb7-efb4ef797492}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BrokenCalculator IMPLEMENTS ISum]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Sum" Id="{3d36953f-2065-4b1a-bf50-4e1589a6f50b}">
      <Declaration><![CDATA[(*This method adds two DINT numbers and returns the result in Sum*)
METHOD Sum : DINT
VAR_INPUT
	Dint1 : DINT;
	Dint2 : DINT;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[Sum := Dint1 * Dint2;]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="BrokenCalculator">
      <LineId Id="9" Count="0" />
    </LineIds>
    <LineIds Name="BrokenCalculator.Sum">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>