<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.6">
  <POU Name="MAIN" Id="{fe27a7e1-9005-4eae-9b1e-49589e7748de}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	TestSuite : TestSuite;
	CalculatorTest : CalculatorTest;
	BrokenCalculatorTest: BrokenCalculatorTest;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[TcUnit.RUN();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>